spring:
  application:
    name: photo-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/photo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: photo-insta
      username: root
      password: example
      auto-index-creation: true
      authentication-database: admin

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka